### ISSUE TITLE
Stellar Staging - Conversion failed

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#104]
**Repro steps**
1) Create revine 3bot account
2) Have daily wallet with nothing on it
3) have staging wallet with 3 transactions, 1 locked tomorrow, 1 locked in 2034, one not locked
4) lock the wallets
5) put stellar online
6) open the app to trigger the conversion

**Expected Result**
conversion works

**Actual Result**
![bRCpXR0PVa](https://user-images.githubusercontent.com/59569757/80985542-a7eaa000-8e2f-11ea-9dc9-a010ef48b858.gif)

**System Info**

**Comment by ken-de-moor** [comment]
See discord search for this issue to find dev seed

**Comment by JonasWijne** [comment]
there are multiple same unhappy paths with diffrent error code , fixed by adding error handling to that unhappy path
