### ISSUE TITLE
After converting 4 wallets, the wallet is stuck on initializing

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#105]
**Repro steps**
1) Create 4 wallets on revine, each with 1 TFT
2) Lock all 4
3) Start stellar wallet

**Expected Result**
All converted and wallet main screen is shown

**Actual Result**
After restarting the app, wallets were converted and shown correctly, but I was stuck in initializing for over 3 minutes before I Just killed the app.

![n19hpRrbbV](https://user-images.githubusercontent.com/59569757/81044130-035e7180-8eb4-11ea-9c9a-d5c42167b3ae.gif)

**System Info**

**Comment by tobiaschielens** [comment]
When trying to convert accounts, all calls are serialized on the conversion service. This resulting in slow calls and long load time https://github.com/threefoldfoundation/tft-stellar/issues/122
