### ISSUE TITLE
Stellar Staging - After converting wallet with locked tokens, the tokens are gone

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#108]
**Repro steps**
1) Have a revine account with 1 daily wallet with no TFT, 1 savings wallet with 3 transactions, 1 non locked, 1 locked 2020, 1 locked 2021
2)  Change to stellar

**Expected Result**
Account with 1 TFTA locked, 1 TFTA unlocked, 1 TFT locked

**Actual Result**
No tokens at all on the stellar version. 0 for every currency
5 minutes later after refreshes and after jonasWijne retrying some things, 1 TFTa popped up

**System Info**

**Comment by tobiaschielens** [comment]
Should be fixed with re-opening the wallet by this issue: https://github.com/threefoldtech/3bot_wallet/issues/99

**Comment by ken-de-moor** [comment]
@tobiaschielens did an entirely new case, converting 6 wallets, everything converted correctly except the locked tokens I had on one wallet. Both the locked in 2020 and in 2021 are nowhere to be seen,

I have restarted the wallet twice and still nothing

**Comment by ken-de-moor** [comment]
Issue https://github.com/threefoldfoundation/tft-stellar/issues/130 needs to be resolved to fix this
