### ISSUE TITLE
Integration Liquid Quick Exchange into 3Bot wallet ?

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#109]
Liquid proposed new feature (will go live end of May), Liquid Quick Exchange, and asks whether useful to integrate APIs into 3Bot wallet. 
Possibility to have quick exchange, link to credit card, no KYC up to 150USD, KYC widget available for amounts above. Possibility to use API for more deep integration, with custom US. 

Does it make sense to integrate APIs to allow credit card purchases. 

Info (see https://circles.threefold.me/project/adnanf-tde/us/83?kanban-status=21): 
API Docs: https://docs.partners.liquid.com
Contact person within Liquid: t.me/marisamcknight

**Comment by jdelrue** [comment]
- It's going through a very centralized channel for transactions, but that's more of a strategic discussion
- Technically it's probably not too difficult, however, there are a lot of other features we want to implement in the wallet as well so it's going to depend on priorities
