### ISSUE TITLE
Stellar Staging - When not entering a message, validation is incorrect

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#116]
1) Restart the wallet
2) Send a transaction without message

Expected: 
Works, message should be optional

Actual: 
Sometimes it works, but after a restart it is mandatory again, with an incorrect error.

![image](https://user-images.githubusercontent.com/59569757/81559323-7a51a980-938f-11ea-897d-e4983c59102c.png)

**Comment by tobiaschielens** [comment]
Should be resolved by https://github.com/threefoldtech/3bot_wallet/commit/e0cb0e3715f65b40f8008f922ed9409a9e9ea7f7
@ken-de-moor I deployed it to staging can you test if this doesn't have any unwanted side effects?
