### ISSUE TITLE
Locked Tokens not displayed right

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/3bot_wallet#122]
in the wallet front screen you only see the amount which will be unlocked next. if you click on wallet details you see all the locked tfta and tft (the ones which will release after jan 1st 2020).
Can you please get all locked tft to the wallets front screen?

**Comment by tobiaschielens** [comment]
In the home screen, you see all the unlocked tokens. The tokens that you already can use to do transactions. When you go to the details view you are able to see all the locked tokens. Displaying all the locked in the home screen makes the home screen unclear
