### ISSUE TITLE
Locked balances are not calculated correctly

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/3bot_wallet#127]
stellar address: `GBKY3B7YNXCB4DJEOPQU5H43GHPZJYGZI3UTNJGZBM4ZVKKNHI7CFR63`
<img width="311" alt="Screenshot 2020-05-25 at 10 53 00" src="https://user-images.githubusercontent.com/3511318/82796611-155d7f80-9e76-11ea-9712-db5d0fc3f8d6.png">
When I calculate the balances using the jsx commandline client for this address, I get:
 TFTA: 838736.0769547
locked TFTA: 1752326.9925925
locked TFT: 1657247.7829217

**Comment by jdelrue** [comment]
@JonasWijne @tobiaschielens please check

**Comment by robvanmieghem** [comment]
sorry, my bad, thanks for helping me find a bug in the jsx client: https://github.com/threefoldtech/jumpscaleX_libs/commit/3aa5978a77c66c061cd05e30b8b67203c32db356
