### ISSUE TITLE
Add extra wallet features using Pkid

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/3bot_wallet#136]
In order to improve the user experience, the PKID functionality needs to be extended.

- [ ] Search wallets based on 3bot name
    - [ ] Be able to mark wallets as public
        - [ ] On the first visit, ask users specifically to mark wallets public or not
    - [ ] Be able to search 3bot name and list the public wallets
- [ ] Save transaction messages encrypted on PKID
    - [ ] Be able to choose to send the message encrypted or as plain text (other apps such as liquid won't be able to read the message )
    - [ ] Make it clear when the encrypted message needs to be fetched from PKID
    - [ ] Be able to store the messages on PKID

**Comment by despiegk** [comment]
need to be careful how we do this, lets discuss

**Comment by jdelrue** [comment]
This is postponed in favor of KYC
