### ISSUE TITLE
Threefold Connect app crashed after paying with QR code. 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#168]
Crash on testnet with iPhone 12 (iOS 14), after button 'Confirm'. 
Payment of 3bot deployment on testnet https://deploy3bot.testnet.grid.tf/threebot_deployer/#/ 

Remark: QR code was generated hours ago. It might have been expired. Non-expired QR code worked well with the same device.

**Comment by ken-de-moor** [comment]
Been live on prod now ,doesn't seem to happen on the prod version. Probably some issue in that specific testnet build.
