### ISSUE TITLE
Stellar - The wallet should be made production ready.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#43]
To do

- [x] There should be a production config.
- [x] Production CI should be set up.
- [x] There should be checks in place to notify when something goes wrong in production.

**Comment by jdelrue** [comment]
CI is ready; config to be changed to prod when its available.

**Comment by jdelrue** [comment]
@robvanmieghem When can we expect prod config?

**Comment by jdelrue** [comment]
Issuer account is on github.com (where?) 

Domain for services subdomain, temp server probably 

ETA april 22

**Comment by tobiaschielens** [comment]
https://github.com/threefoldfoundation/tft-stellar

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar#production-services
