### ISSUE TITLE
Stellar - wallet should be testable on an external staging server.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#44]
- [x] external staging for wallet should be created
- [ ] ~there should be a faucet that allows 100 million or more TFT to be generated for testing~

**Comment by jdelrue** [comment]
@MathiasDeWeerdt

**Comment by jdelrue** [comment]
Mathias will do when FFC dev is going smoothly

**Comment by ken-de-moor** [comment]
@robvanmieghem could you kindly provide input on the second point ' there should be a faucet that allows 100 million or more TFT to be generated for testing' ?

**Comment by robvanmieghem** [comment]
@ken-de-moor why do you need 100M or more? Instead of the faucet, they can already be acquired today, still needs to be documented: https://github.com/threefoldfoundation/tft-stellar/issues/54

**Comment by ken-de-moor** [comment]
> @ken-de-moor why do you need 100M or more? Instead of the faucet, they can already be acquired today, still needs to be documented: [threefoldfoundation/tft-stellar#54](https://github.com/threefoldfoundation/tft-stellar/issues/54)

We had a specific issue in production before that only happened for wallets with 1 milion or more tokens, due to limited test tokens we never noticed this issue. It's best to always test with more tokens than in production scenarios to avoid things like this happening again.

Thanks for the linked issue I'll pass it on to our devs

**Comment by robvanmieghem** [comment]
Tetstnet tft orderbook: https://stellar.expert/explorer/testnet/asset/TFT-GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3?filter=orderbook

**Comment by robvanmieghem** [comment]
@ken-de-moor  for the 1M or more test, ping me and I'll send them

**Comment by jdelrue** [comment]
@MathiasDeWeerdt will add env on april 6

**Comment by jdelrue** [comment]
Env is done! See PIN in general channel

**Comment by jdelrue** [comment]
Waiting for faucet

**Comment by jdelrue** [comment]
@robvanmieghem will provide 100million tokens, please add address here to receive @ken-de-moor
