### ISSUE TITLE
Stellar - Accounts should be created for every new 3bot user

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#47]
- [x] There should be a service that can be called to create new accounts
- [x] This service needs to be called for every newly created 3botaccount
- [x] Improve UX -> error page for SMS is bad

**Comment by jdelrue** [comment]
+ Link to doc 
+ Why blocked?

**Comment by jdelrue** [comment]
Uncommitted @JonasWijne

**Comment by jdelrue** [comment]
@KristofVanstappen Need copywrite for "Please send SMS to and click here when done"
