### ISSUE TITLE
Stellar - Transactions should be implemented and improved

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#48]
- [x] Make it possible to send transactions
- [x] Make it possible to see transactions
- [x] Fund transactions
- [x] Validate transaction responses
- [x] Make transactions realtime
- [x] Improve realtime transactions

**Comment by jdelrue** [comment]
First step: Check operations, next step: rebuild transaction, take TFT signature and validate to equal

So for this story we will only check the operations

**Comment by tobiaschielens** [comment]
pull request has been made
