### ISSUE TITLE
Stellar - downtime should be handled correctly

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#50]
- [x] Clearly inform the user what goes wrong when there is a connection issue
- [x] Make sure all data is stored in a way that any downtime does not cause data loss
- [x] Make it possible to reload when connection restores, without forcing an app restart

**Comment by jdelrue** [comment]
- PKID downtime
- TF API downtime
_- Stellar downtime for next version_

@MathiasDeWeerdt

**Comment by jdelrue** [comment]
uncommitted changes @JonasWijne to commit

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/79356039-bf282300-7f3e-11ea-87f1-656908cb807c.png)

**Comment by tobiaschielens** [comment]
@ken-de-moor this screenshot is in fact an error in the app and not the wallet.
