### ISSUE TITLE
Stellar - There should be a custom loading spinner displaying exactly what is loading

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#53]
- [x] Add text to the loading spinner
- [x] Make the text specifically change based on what is loading at that moment
- [x] Make pretty / fix css

**Comment by jdelrue** [comment]
@tobiaschielens

**Comment by jdelrue** [comment]
Text is added and changed but still ugly

**Comment by tobiaschielens** [comment]
https://github.com/threefoldtech/3bot_wallet/compare/stellar...stellar_loadingMessages?expand=1 Ready for @JonasWijne to review
