### ISSUE TITLE
Transaction fee is being shown as a transaction

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/3bot_wallet#57]
The fee is being shown as a transaction in the wallet. 
Possible fixes: 
 Filter out payments with destination (GAKONCKYJ7PRRKBZSWVPG3MURUNX4H44AB3CU2YGVKF2FD7KXJBB3XID) in staging
![image](https://user-images.githubusercontent.com/17977313/78023844-aec95300-7357-11ea-90a6-5d79cdc93ad1.png)

**Comment by jdelrue** [comment]
@JonasWijne will post howto

**Comment by JonasWijne** [comment]
You can bundle based on transaction hash

**Comment by JonasWijne** [comment]
right now these "fee transactions" are filtered out and fee is hardecoded as 0.1 tft could be changed in future
