### ISSUE TITLE
20/12 - v1.0.1-redesign - bugs

### ISSUE THREAD

**Issue by azertyalex** [threefoldtech/3bot_wallet#6]
# Bugs
## 1. When swapping wallet form is empty
**Steps to reproduce:**
- Go to transfer screen
- fill in data
- change from address
- form data is cleared

**What should happen:**  
form data should not be cleared, only `from` wallet address should be changed.
==> MINOR
~~## 2. Scan QR code return button goes to 3botconnect home screen
Should go back to transfer screen~~

## 3. Invalid wallet amount after sending transaction
When you have 300TFT in your wallet (via faucet) and send 20TFT to another address, you balance shows as 0TFT
==> MINOR 

~~## 4. Wallet is in front of login pincode
Steps to reproduce:- Open app- Go to wallet- Lock phone- Try login on pc- Unlock phoneThe login creen is now hidden behind the wallet screen~~

**Comment by KristofVanstappen** [comment]
- skip in wizard not working
- first screen in wizard typo 3bot => 3Bot
- When registered, back button is not working. I need to restart te app
- Opening wallet for first time, error message for a few milliseconds
- remove chat icon in social
- when clicking settings => wizard is opening

**Comment by KristofVanstappen** [comment]
create/import wallet
 - title size is larger than other titles
 - android back button is not working

**Comment by KristofVanstappen** [comment]
wallet open, 
eat my dinner, back to app
no bottom menu in app, wallet is not responding
![image](https://user-images.githubusercontent.com/7849505/71279956-52b76180-235a-11ea-9aa5-1be5af9dd621.png)

**Comment by KristofVanstappen** [comment]
scan qr => android back button

![image](https://user-images.githubusercontent.com/7849505/71283859-a9746980-2361-11ea-9d21-15c4da32606c.png)

**Comment by azertyalex** [comment]
I send you 10 potatos

<details>
<summary>Screenshot</summary

![image](https://user-images.githubusercontent.com/9082988/71287448-ad57ba00-2368-11ea-8706-2cfcb409fdf6.png)


</details>

**Comment by ken-de-moor** [comment]
old ticket, not linked, new issues will be created if needed
