### ISSUE TITLE
Stellar Staging - When dragging to re-order wallets, the copy/paste menu pops up.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#63]
**Repro steps**
1) Drag to re-order wallets

**Expected Result**
No copy paste menu on this page, none of the text is selectable anyway.

**Actual Result**
Copy paste menu pops up while re-ordering wallets.

**System Info**

**Comment by jdelrue** [comment]
Disable copy paste om main screen as temp workaround?

**Comment by tobiaschielens** [comment]
Did implement a window.NoCopyPaste on start dragging, seems to be ok for now

**Comment by ken-de-moor** [comment]
Re-opened, re-order seems to be broken entirely now
