### ISSUE TITLE
Stellar Staging - Failed to import wallet

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#65]
**Repro steps**
1) Import wallet from old threefold app, before stellar conversion
2) Example staging seed phrase : `suggest loyal taxi pluck grab celery solar gentle kitchen link build opinion end cement flight stereo good pluck august lava patch awake stamp retire`

**Expected Result**
Wallet imported and transferred

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/78871679-5a556000-7a48-11ea-90f7-005ab5359f8c.png)

**System Info**

**Comment by jdelrue** [comment]
Could be because of intervention / server downtime

**Comment by ken-de-moor** [comment]
error still happening now, exactly the same

**Comment by jdelrue** [comment]
Not because of network issues, please check ASAP

**Comment by tobiaschielens** [comment]
Blocked by https://github.com/threefoldfoundation/tft-stellar/issues/96

**Comment by jdelrue** [comment]
Account is NOT locked, this causes convert to fail. TF service should lock.

**Comment by JonasWijne** [comment]
@ken-de-moor, can you test again on staging, it could be potentially fixed by other issue ?

**Comment by tobiaschielens** [comment]
Blocked by https://github.com/threefoldfoundation/tft-stellar/issues/96

**Comment by tobiaschielens** [comment]
All is unblocked and seed can be imported now
