### ISSUE TITLE
Stellar Staging - When pressing back on the transaction details, you are taken too far back.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#70]
**Repro steps**
1) Select a wallet
2) Select a transaction in that wallet to see the message
3) Use the back button provided in the app ( not the cross )

**Expected Result**
Returned to previous screen, transactions of the wallet

**Actual Result**
Returned to wallet overview

**System Info**

**Comment by JonasWijne** [comment]
you are always redirected to "HOME"

**Comment by ken-de-moor** [comment]
Shows as a popup now, clearer that it should be closed instead of returned
