### ISSUE TITLE
Stellar Staging - Error converting a tfchain wallet to a Stellar account

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#71]
![IMG_2214](https://user-images.githubusercontent.com/30384423/78982388-539b1b80-7b22-11ea-92ab-8d94fd7e3980.PNG)
![IMG_2215](https://user-images.githubusercontent.com/30384423/78982395-55fd7580-7b22-11ea-9669-cc50187c455f.PNG)

**Comment by tobiaschielens** [comment]
![image](https://user-images.githubusercontent.com/17977313/79724733-4c28fe80-82e8-11ea-8ac0-db0c17a228cb.png)
Tried to import this seed on my client and it worked, not sure what was wrong here. Any idea if there where unconfirmed transactions? Can you try to import the seed again? If you run into this again please let us know.

**Comment by gmachtel** [comment]
Imported and now it works. But isn't the situation different now, i.e. account already existing on Stellar ? Anyway, problem seems to be solved as you were able to import.

**Comment by tobiaschielens** [comment]
Yes, thats true but was able to import it through our app.
