### ISSUE TITLE
Wallet should support multi currencies

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/3bot_wallet#72]
The wallet should support multiple currencies (assets)
A users should:
- [x] Be able to see balances for multiple currencies
- [x] Filter transactions on currency
- [x] Do payments in different currencies
- [x] Add currency (trustline) to account
- [x] Implement multi currency in QR scan

**Comment by tobiaschielens** [comment]
Question: How are we going to handle on the fly adding currencies? Adding a currency does imply that each account has to create a new trustline. Will we do this automatically or will the user have to interfere in order to do this? Will this service be for free or does the user have to pay for this?

**Comment by ken-de-moor** [comment]
@tobiaschielens I added a checkbox for multi currency in QR, currently it does not allow for free TFT to be received

**Comment by ken-de-moor** [comment]
When moved to other project it wasn't correctly put on the board, @tobiaschielens can you update this? I think everything in this story is ready and can be put on verification
