### ISSUE TITLE
Importing a tfchain wallet keeps on spinning

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#73]
Behaviour: 
- First an error 'failed to import an account'
- Then after push reload button, it keeps on spinning
- After 5min pushed the Devview button and restarted wallet in Actions, but the account linked to the seed keys did not appear
Used device: iPhone7
Seed keys: "exist orchard debris broccoli rural resemble noble script whisper still scrub bike color glimpse attack try ride treat loop shallow asset task enter seed"
![IMG_2216](https://user-images.githubusercontent.com/30384423/79001153-45fb8b00-7b4e-11ea-951f-0cfa600cfbcb.PNG)
![IMG_2217](https://user-images.githubusercontent.com/30384423/79001162-48f67b80-7b4e-11ea-92ef-0aecae653671.PNG)
![IMG_2218](https://user-images.githubusercontent.com/30384423/79001164-498f1200-7b4e-11ea-877a-1c30da98610c.PNG)

**Comment by gmachtel** [comment]
Failing import:   `curl 'https://testnet.threefold.io/threefoldfoundation/conversion_service/activate_account' \
  -H 'authority: testnet.threefold.io' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://localhost:8080' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://localhost:8080/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-binary '{"args":{"tfchain_address":"012edfe6f8c48d29be724edd6ee09a3d47ea825ee29a796bf3274e9e7f3ff480fc4a04307c4596","address":"GD5FYYYQC3DA3ETCSIGJMW3O33P4ZIXB4X6RQ2KLBDOJG66O3SDM6KHU"}}' \
  --compressed` Gives a return 400

**Comment by DylanVerstraete** [comment]
Stellar address `GD5FYYYQC3DA3ETCSIGJMW3O33P4ZIXB4X6RQ2KLBDOJG66O3SDM6KHU` is not found on the stellar testnet.

https://laboratory.stellar.org/#explorer?resource=accounts&endpoint=single&values=eyJhY2NvdW50X2lkIjoiR0Q1RllZWVFDM0RBM0VUQ1NJR0pNVzNPMzNQNFpJWEI0WDZSUTJLTEJET0pHNjZPM1NETTZLSFUifQ%3D%3D&network=test

**Comment by gmachtel** [comment]
Import successful ! Solved with commit https://github.com/threefoldfoundation/tft-stellar/commit/af5b98c1f8fb93de3bb69c0efb7c957e55ce731b
