### ISSUE TITLE
Stellar Staging - Transfer between tokens on testnet leads to error (timeout ?)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#75]
![image](https://user-images.githubusercontent.com/30384423/79307615-7a2cce00-7ef7-11ea-8d05-56dead1049bd.png)

**Comment by tobiaschielens** [comment]
The funded transaction response has been changed and the XDR is now in result.data.transaction_xdr. This fixes the error. However, transactions do take a lot of time to be done. On mobile, it seems to be timing out. We are investigating this

**Comment by ken-de-moor** [comment]
@tobiaschielens my transactions appear to be working at the moment, can this be moved to verification or are there still issues?

**Comment by tobiaschielens** [comment]
We disabled the watchers on balance and transactions for now. It fixes the transaction for now. However, it means that we are not able to auto-update the balance at the moment. We can keep it open until that is fixed.

**Comment by JonasWijne** [comment]
should be fixed with making calls on more specific times
