### ISSUE TITLE
Stellar Staging - Currency is shown in send even when the user doesn't have that currency, results in no From accounts to be selectable.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#84]
**Repro steps**
1) Have an account with no FreeTFT
2) Attempt to send FreeTFT

**Expected Result**
Option should not exist in the currency dropdown, only display currencies the user actually owns in the send transaction.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/80004067-2e16f600-84c2-11ea-9197-d34db0ac0b11.png)

**System Info**

**Comment by tobiaschielens** [comment]
It should not be possible to now convert an account without having FreeTFT then. Please let me know if that is the case.
