### ISSUE TITLE
Stellar Staging - Balance still shows as 0 after transferring TFT

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#86]
**Repro steps**
1) Transfer 1 TFT from imported wallet b to imported wallet Q
2) Check balance and transactions

**Expected Result**
If the transaction appears in the transactions list, it should update the balance.

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/80004974-48050880-84c3-11ea-8ffd-400ab40faa9e.png) 
![image](https://user-images.githubusercontent.com/59569757/80004993-4dfae980-84c3-11ea-8442-749ddfcf58e4.png)

**System Info**

**Comment by JonasWijne** [comment]
watchers were disabled, should be fixed now
