### ISSUE TITLE
Stellar - Testnet account should receive 2Billion TFT and FreeTFT

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#90]
Following wallet should have 2 Billion TFT and FreeTFT on Stellar Testnet
GCTZGKBNYY4VYUDDSUS6NUO5KWHH4A7OWZN4BLO4TTQYSFT3PZZZSHJV

**Comment by robvanmieghem** [comment]
@ken-de-moor  off course.  tft is sent, please add a trustline to freetft

**Comment by ken-de-moor** [comment]
@robvanmieghem trustline for freeTFT has been added

**Comment by robvanmieghem** [comment]
done
