### ISSUE TITLE
Stellar Staging - Certain transaction amounts result in payment failed

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#92]
**Repro steps**
1) Send a transaction for 123123123 TFT
2) Send a transaction for 0e1 TFT

**Expected Result**
They both work

**Actual Result**
Both result in payment failed, enough funds is available

**System Info**

**Comment by ken-de-moor** [comment]
The wierd thing is that sending 1b tft through 10e8 notation does work, but writing it all out and sending 123123123 does not, which is a lower amount

**Comment by jdelrue** [comment]
@ken-de-moor  Please reproduce and sync with @JonasWijne

**Comment by ken-de-moor** [comment]
Works now

**Comment by ken-de-moor** [comment]
Fails with 1.87b, dev key provided in discord

**Comment by tobiaschielens** [comment]
Blocked by https://github.com/threefoldfoundation/tft-stellar/issues/123

**Comment by tobiaschielens** [comment]
This issue should be fixed
