### ISSUE TITLE
Activation service returnes 400 after 9 minutes

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/3bot_wallet#95]
When running `activate_account` on an account which has no TFT on rivine this returnes 400 after 9 min
## Request:
```bash
curl 'https://tokenservices.threefold.io/threefoldfoundation/conversion_service/activate_account' \
  -H 'authority: tokenservices.threefold.io' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://wallet-beta.jimber.org' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://wallet-beta.jimber.org/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-binary '{"args":{"tfchain_address":"01b0096e16b1765995cda22bdccf7b44542ead4f82f8102e3a0c8d54a674df636f076b3b5e35b7","address":"GCYJU26PRR3KWLK2JFIREZWGVRMHJPDQFU6QBXE7SCUPEFNSNGSMHKK7"}}' \
  --compressed
```

## Parameters:
* tfchain_address : `01b0096e16b1765995cda22bdccf7b44542ead4f82f8102e3a0c8d54a674df636f076b3b5e35b7` (does not have any tft)
* address: `GCYJU26PRR3KWLK2JFIREZWGVRMHJPDQFU6QBXE7SCUPEFNSNGSMHKK7` (not yet created)

## Response: 
```json
{
    "error": "/explorer/hashes/01b0096e16b1765995cda22bdccf7b44542ead4f82f8102e3a0c8d54a674df636f076b3b5e35b7: no explorer was available"
}
```

**Comment by DylanVerstraete** [comment]
This is due to tfchain explorer issues we are having right now. Lee is investigating.

**Comment by LeeSmet** [comment]
> This is due to tfchain explorer issues we are having right now. Lee is investigating.

This is actually not true. What I'm investigating is issues with the block creators. This does not affect the explorer in any way.

From what I see in the monitoring, explorers have been reachable fine for the past 24 hours.

**Comment by tobiaschielens** [comment]
Please note that this is happening on mainnet. On tes net this is working fine.

**Comment by LeeSmet** [comment]
Solved by https://github.com/threefoldfoundation/tft-stellar/issues/121#issuecomment-623914673
